import mongoose from "mongoose";

const FieldConfigurationSchema = new mongoose.Schema(
  {
    id: { type: mongoose.Schema.Types.ObjectId },
    fieldName: { type: String, required: true },
    fieldType: { type: String, required: true },
    fieldLabel: { type: String, required: true },
    isRequired: { type: Boolean, default: false },
    width: { type: String, enum: ["full", "flex"], default: "full" },
    icon: { type: String, default: null },
    sequence: { type: Number, default: 0, required: true },
    options: { type: [String], default: [] },
    fixedField: { type: Boolean, default: false },
  },
  { timestamps: true }
);
export const defaultItemFieldConfigurations = [
  {
    fieldName: "purchase_order",
    fieldType: "text",
    fieldLabel: "Purchase Order",
    isRequired: true,
    width: "flex",
    icon: "",
    sequence: 1,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "description",
    fieldType: "text",
    fieldLabel: "Vehicle Description",
    isRequired: true,
    width: "flex",
    icon: "",
    sequence: 2,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "quantity",
    fieldType: "number",
    fieldLabel: "Quantity",
    isRequired: true,
    width: "flex",
    icon: "",
    sequence: 3,
    options: [],
    fixedField: true,
  },
];
export const defaultFieldConfigurations = [
  {
    fieldName: "vehicle_number",
    fieldType: "text",
    fieldLabel: "Vehicle Number",
    isRequired: true,
    width: "full",
    icon: "Truck",
    sequence: 1,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "driver_name",
    fieldType: "text",
    fieldLabel: "Driver Name",
    isRequired: true,
    width: "flex",
    icon: "User",
    sequence: 3,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "transporter_name",
    fieldType: "text",
    fieldLabel: "Transporter Name",
    isRequired: true,
    width: "full",
    icon: "Package",
    sequence: 3,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "license_number",
    fieldType: "text",
    fieldLabel: "License Number",
    isRequired: true,
    width: "flex",
    icon: "IdCard",
    sequence: 4,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "in_date",
    fieldType: "date",
    fieldLabel: "In Date",
    isRequired: true,
    width: "flex",
    icon: "Calendar",
    sequence: 5,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "lr_date",
    fieldType: "date",
    fieldLabel: "Lorry Receipt Date",
    isRequired: true,
    width: "flex",
    icon: "Calendar",
    sequence: 6,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "lr_number",
    fieldType: "text",
    fieldLabel: "Lorry Receipt Number",
    isRequired: true,
    width: "flex",
    icon: "FileText",
    sequence: 7,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "comments",
    fieldType: "textarea",
    fieldLabel: "Comments",
    isRequired: false,
    width: "full",
    icon: "MessageSquare",
    sequence: 8,
    options: [],
    fixedField: true,
  },
];

export const defaultWeightInFieldConfigurations = [
  {
    fieldName: "vehicle_number",
    fieldType: "text",
    fieldLabel: "Vehicle Number",
    isRequired: true,
    width: "flex",
    icon: "truck",
    sequence: 1,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "driver_name",
    fieldType: "text",
    fieldLabel: "Driver Name",
    isRequired: true,
    width: "flex",
    icon: "user",
    sequence: 2,
    options: [],
    fixedField: false,
  },
  {
    fieldName: "product_type",
    fieldType: "select",
    fieldLabel: "Product Type",
    isRequired: true,
    width: "flex",
    icon: "box",
    sequence: 3,
    options: ["Sand", "Gravel", "Cement", "Steel"],
    fixedField: false,
  },
  {
    fieldName: "gross_weight",
    fieldType: "number",
    fieldLabel: "Gross Weight (kg/t)",
    isRequired: true,
    width: "flex",
    icon: "scale",
    sequence: 4,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "tare_weight",
    fieldType: "number",
    fieldLabel: "Tare Weight (kg/t)",
    isRequired: true,
    width: "flex",
    icon: "scale",
    sequence: 5,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "in_time",
    fieldType: "date",
    fieldLabel: "Time In",
    isRequired: true,
    width: "flex",
    icon: "clock",
    sequence: 6,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "remarks",
    fieldType: "textarea",
    fieldLabel: "Remarks/Notes",
    isRequired: false,
    width: "full",
    icon: "note",
    sequence: 7,
    options: [],
    fixedField: false,
  },
];

export const defaultWeightOutFieldConfigurations = [
  {
    fieldName: "vehicle_number",
    fieldType: "text",
    fieldLabel: "Vehicle Number",
    isRequired: true,
    width: "flex",
    icon: "truck",
    sequence: 1,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "driver_name",
    fieldType: "text",
    fieldLabel: "Driver Name",
    isRequired: true,
    width: "flex",
    icon: "user",
    sequence: 2,
    options: [],
    fixedField: false,
  },
  {
    fieldName: "inTicketId",
    fieldType: "text",
    fieldLabel: "Linked In Ticket ID",
    isRequired: true,
    width: "full",
    icon: "ticket",
    sequence: 3,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "tareWeight",
    fieldType: "number",
    fieldLabel: "Tare Weight (kg/t)",
    isRequired: true,
    width: "flex",
    icon: "scale",
    sequence: 4,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "netWeight",
    fieldType: "number",
    fieldLabel: "Net Weight (kg/t)",
    isRequired: false,
    width: "flex",
    icon: "balance",
    sequence: 5,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "outTime",
    fieldType: "date",
    fieldLabel: "Time Out",
    isRequired: true,
    width: "flex",
    icon: "clock",
    sequence: 6,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "remarks",
    fieldType: "textarea",
    fieldLabel: "Remarks/Notes",
    isRequired: false,
    width: "full",
    icon: "note",
    sequence: 7,
    options: [],
    fixedField: false,
  },
];
export const AnalyticsConfigurationSchema = [
  { fieldName: "vehicle_number", fieldLabel: "Vehicle No", sequence: 2 },
  { fieldName: "gateEntryNumber", fieldLabel: "Gate Entry ID", sequence: 1 },
  { fieldName: "driver_name", fieldLabel: "Driver Name", sequence: 3 },
  { fieldName: "entry_type", fieldLabel: "Type", sequence: 4 },
  { fieldName: "transporter_name", fieldLabel: "Vendor", sequence: 5 },
  { fieldName: "in_date", fieldLabel: "Gate In", sequence: 6 },
  { fieldName: "out_date", fieldLabel: "Gate Out", sequence: 7 },
  { fieldName: "duration", fieldLabel: "Duration", sequence: 8 },
  { fieldName: "status", fieldLabel: "Status", sequence: 9 },
  { fieldName: "location", fieldLabel: "Current location", sequence: 10 },
  { fieldName: "weight", fieldLabel: "Weight", sequence: 11 },
  { fieldName: "remarks", fieldLabel: "Remarks", sequence: 9 },
];
export default FieldConfigurationSchema;
