import mongoose from "mongoose";

const FieldConfigurationSchema = new mongoose.Schema(
  {
    id: { type: mongoose.Schema.Types.ObjectId },
    fieldName: { type: String, required: true },
    fieldType: { type: String, required: true },
    fieldLabel: { type: String, required: true },
    isRequired: { type: Boolean, default: false },
    width: { type: String, enum: ["full", "flex"], default: "full" },
    icon: { type: String, default: null },
    sequence: { type: Number, default: 0, required: true },
    options: { type: [String], default: [] },
    fixedField: { type: Boolean, default: false },
  },
  { timestamps: true }
);

export const defaultFieldConfigurations = [
  {
    fieldName: "vehicle_number",
    fieldType: "text",
    fieldLabel: "Vehicle Number",
    isRequired: true,
    width: "full",
    icon: "Truck",
    sequence: 1,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "driver_name",
    fieldType: "text",
    fieldLabel: "Driver Name",
    isRequired: true,
    width: "flex",
    icon: "User",
    sequence: 3,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "transporter_name",
    fieldType: "text",
    fieldLabel: "Transporter Name",
    isRequired: true,
    width: "full",
    icon: "Package",
    sequence: 3,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "license_number",
    fieldType: "text",
    fieldLabel: "License Number",
    isRequired: true,
    width: "flex",
    icon: "IdCard",
    sequence: 4,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "in_date",
    fieldType: "date",
    fieldLabel: "In Date",
    isRequired: true,
    width: "flex",
    icon: "Calendar",
    sequence: 5,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "lr_date",
    fieldType: "date",
    fieldLabel: "Lorry Receipt Date",
    isRequired: true,
    width: "flex",
    icon: "Calendar",
    sequence: 6,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "lr_number",
    fieldType: "text",
    fieldLabel: "Lorry Receipt Number",
    isRequired: true,
    width: "flex",
    icon: "FileText",
    sequence: 7,
    options: [],
    fixedField: true,
  },
  {
    fieldName: "comments",
    fieldType: "textarea",
    fieldLabel: "Comments",
    isRequired: false,
    width: "full",
    icon: "MessageSquare",
    sequence: 8,
    options: [],
    fixedField: true,
  },
];

export default FieldConfigurationSchema;
